apiVersion: apps/v1
kind: Deployment
metadata:
  name: club-deployment-COLOR_PLACEHOLDER
  labels:
    app: club-service
    color: COLOR_PLACEHOLDER
spec:
  replicas: 2
  selector:
    matchLabels:
      app: club-service
      color: COLOR_PLACEHOLDER
  template:
    metadata:
      labels:
        app: club-service
        color: COLOR_PLACEHOLDER
    spec:
      containers:
      - name: club-service
        image: IMAGE_PLACEHOLDER
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "mysql+pymysql://root:password@mysql-service:3306/unipiper"
